export const SUPABASE_URL = "https://vunhptryfmkcevbkyuko.supabase.co";

export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1bmhwdHJ5Zm1rY2V2Ymt5dWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA3Mjg3MTYsImV4cCI6MjA0NjMwNDcxNn0.G035CqiWfwNdMgiKHIdRkOm2P2HHeRL4EB-Uocad8R8";
