export const SUPABASE_URL = "https://wfckkvltzcssotvuevly.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmY2trdmx0emNzc290dnVldmx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1Nzk5NDAsImV4cCI6MjA3ODE1NTk0MH0.yZ2eRaBNvqu0AFgz1U5tYUb7tpZKFFXFCLZfBEjsin4";
